# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Opening.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Opening_Window(object):
    def setupUi(self, Opening_Window):
        Opening_Window.setObjectName("Opening_Window")
        Opening_Window.resize(830, 756)
        self.centralwidget = QtWidgets.QWidget(Opening_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setGeometry(QtCore.QRect(0, 0, 801, 731))
        self.main_tab.setObjectName("main_tab")
        self.main_process = QtWidgets.QWidget()
        self.main_process.setObjectName("main_process")
        self.main_process1 = QtWidgets.QTabWidget(self.main_process)
        self.main_process1.setGeometry(QtCore.QRect(0, 0, 741, 671))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.main_process1.setFont(font)
        self.main_process1.setTabPosition(QtWidgets.QTabWidget.West)
        self.main_process1.setIconSize(QtCore.QSize(16, 16))
        self.main_process1.setObjectName("main_process1")
        self.simulation_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.simulation_tab.setFont(font)
        self.simulation_tab.setObjectName("simulation_tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.simulation_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(50, 220, 711, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(20, 70, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.save_time_step_yes_radio = QtWidgets.QRadioButton(self.groupBox_4)
        self.save_time_step_yes_radio.setGeometry(QtCore.QRect(120, 70, 41, 17))
        self.save_time_step_yes_radio.setChecked(False)
        self.save_time_step_yes_radio.setObjectName("save_time_step_yes_radio")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(250, 60, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_30.setPalette(palette)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.save_time_step_no_radio = QtWidgets.QRadioButton(self.groupBox_4)
        self.save_time_step_no_radio.setGeometry(QtCore.QRect(190, 70, 41, 17))
        self.save_time_step_no_radio.setChecked(True)
        self.save_time_step_no_radio.setObjectName("save_time_step_no_radio")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(20, 32, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.temp_folder_addr_line = QtWidgets.QLineEdit(self.groupBox_4)
        self.temp_folder_addr_line.setGeometry(QtCore.QRect(120, 30, 331, 20))
        self.temp_folder_addr_line.setReadOnly(True)
        self.temp_folder_addr_line.setObjectName("temp_folder_addr_line")
        self.temp_browser_button = QtWidgets.QPushButton(self.groupBox_4)
        self.temp_browser_button.setGeometry(QtCore.QRect(460, 28, 75, 23))
        self.temp_browser_button.setObjectName("temp_browser_button")
        self.groupBox_5 = QtWidgets.QGroupBox(self.simulation_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(50, 40, 711, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.simulation_time_line = QtWidgets.QLineEdit(self.groupBox_5)
        self.simulation_time_line.setGeometry(QtCore.QRect(150, 20, 81, 20))
        self.simulation_time_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.simulation_time_line.setObjectName("simulation_time_line")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(20, 22, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(20, 100, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.multiple_radio = QtWidgets.QRadioButton(self.groupBox_5)
        self.multiple_radio.setGeometry(QtCore.QRect(190, 100, 101, 17))
        self.multiple_radio.setObjectName("multiple_radio")
        self.single_radio = QtWidgets.QRadioButton(self.groupBox_5)
        self.single_radio.setGeometry(QtCore.QRect(120, 100, 51, 17))
        self.single_radio.setChecked(True)
        self.single_radio.setObjectName("single_radio")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(20, 52, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.simulation_time_step_line = QtWidgets.QLineEdit(self.groupBox_5)
        self.simulation_time_step_line.setGeometry(QtCore.QRect(150, 50, 81, 20))
        self.simulation_time_step_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.simulation_time_step_line.setObjectName("simulation_time_step_line")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(240, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.PlainText)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(240, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setTextFormat(QtCore.Qt.PlainText)
        self.label_18.setObjectName("label_18")
        self.result_folder_addr_line = QtWidgets.QLineEdit(self.groupBox_5)
        self.result_folder_addr_line.setGeometry(QtCore.QRect(120, 130, 331, 20))
        self.result_folder_addr_line.setReadOnly(True)
        self.result_folder_addr_line.setObjectName("result_folder_addr_line")
        self.result_directory_browser_button = QtWidgets.QPushButton(self.groupBox_5)
        self.result_directory_browser_button.setGeometry(QtCore.QRect(460, 130, 75, 23))
        self.result_directory_browser_button.setObjectName("result_directory_browser_button")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(20, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.main_process1.addTab(self.simulation_tab, "")
        self.hudrauics_tab = QtWidgets.QWidget()
        self.hudrauics_tab.setObjectName("hudrauics_tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.hudrauics_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 210, 761, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.wntr_solver_radio = QtWidgets.QRadioButton(self.groupBox_3)
        self.wntr_solver_radio.setEnabled(False)
        self.wntr_solver_radio.setGeometry(QtCore.QRect(240, 50, 82, 17))
        self.wntr_solver_radio.setObjectName("wntr_solver_radio")
        self.modified_epanet_radio = QtWidgets.QRadioButton(self.groupBox_3)
        self.modified_epanet_radio.setEnabled(True)
        self.modified_epanet_radio.setGeometry(QtCore.QRect(80, 50, 151, 17))
        self.modified_epanet_radio.setChecked(True)
        self.modified_epanet_radio.setObjectName("modified_epanet_radio")
        self.minimum_pressure_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.minimum_pressure_line.setGeometry(QtCore.QRect(80, 90, 61, 20))
        self.minimum_pressure_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minimum_pressure_line.setObjectName("minimum_pressure_line")
        self.required_pressure_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.required_pressure_line.setGeometry(QtCore.QRect(80, 130, 61, 20))
        self.required_pressure_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.required_pressure_line.setObjectName("required_pressure_line")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(150, 90, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(150, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 130, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 145, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.hydraulic_time_step_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.hydraulic_time_step_line.setGeometry(QtCore.QRect(80, 160, 61, 20))
        self.hydraulic_time_step_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hydraulic_time_step_line.setObjectName("hydraulic_time_step_line")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(150, 160, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName("label_16")
        self.groupBox_6 = QtWidgets.QGroupBox(self.hudrauics_tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 30, 761, 171))
        self.groupBox_6.setObjectName("groupBox_6")
        self.wdn_addr_line = QtWidgets.QLineEdit(self.groupBox_6)
        self.wdn_addr_line.setGeometry(QtCore.QRect(130, 30, 481, 20))
        self.wdn_addr_line.setReadOnly(True)
        self.wdn_addr_line.setObjectName("wdn_addr_line")
        self.wdn_browse_button = QtWidgets.QPushButton(self.groupBox_6)
        self.wdn_browse_button.setGeometry(QtCore.QRect(630, 30, 75, 23))
        self.wdn_browse_button.setObjectName("wdn_browse_button")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.demand_ratio_line = QtWidgets.QLineEdit(self.groupBox_6)
        self.demand_ratio_line.setGeometry(QtCore.QRect(130, 70, 41, 21))
        self.demand_ratio_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.demand_ratio_line.setObjectName("demand_ratio_line")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(180, 70, 91, 21))
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_8.setObjectName("label_8")
        self.main_process1.addTab(self.hudrauics_tab, "")
        self.damage_tab = QtWidgets.QWidget()
        self.damage_tab.setObjectName("damage_tab")
        self.scenario_table = QtWidgets.QTableWidget(self.damage_tab)
        self.scenario_table.setGeometry(QtCore.QRect(80, 100, 691, 192))
        self.scenario_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.scenario_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.scenario_table.setObjectName("scenario_table")
        self.scenario_table.setColumnCount(6)
        self.scenario_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.scenario_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.scenario_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.scenario_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.scenario_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.scenario_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.scenario_table.setHorizontalHeaderItem(5, item)
        self.scenario_table.horizontalHeader().setDefaultSectionSize(110)
        self.scenario_table.horizontalHeader().setMinimumSectionSize(60)
        self.label_31 = QtWidgets.QLabel(self.damage_tab)
        self.label_31.setGeometry(QtCore.QRect(80, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.add_scenario_button = QtWidgets.QPushButton(self.damage_tab)
        self.add_scenario_button.setGeometry(QtCore.QRect(20, 100, 51, 23))
        self.add_scenario_button.setObjectName("add_scenario_button")
        self.status_text = QtWidgets.QTextBrowser(self.damage_tab)
        self.status_text.setEnabled(True)
        self.status_text.setGeometry(QtCore.QRect(0, 550, 791, 121))
        self.status_text.setObjectName("status_text")
        self.remove_scenario_button = QtWidgets.QPushButton(self.damage_tab)
        self.remove_scenario_button.setGeometry(QtCore.QRect(20, 130, 51, 23))
        self.remove_scenario_button.setObjectName("remove_scenario_button")
        self.groupBox_7 = QtWidgets.QGroupBox(self.damage_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(80, 310, 481, 80))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_13.setEnabled(False)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 30, 91, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_17.setEnabled(False)
        self.pushButton_17.setGeometry(QtCore.QRect(140, 30, 91, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_16.setEnabled(False)
        self.pushButton_16.setGeometry(QtCore.QRect(360, 30, 91, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_15.setEnabled(False)
        self.pushButton_15.setGeometry(QtCore.QRect(250, 30, 91, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.groupBox_8 = QtWidgets.QGroupBox(self.damage_tab)
        self.groupBox_8.setGeometry(QtCore.QRect(80, 420, 691, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pipe_damage_modeling_button = QtWidgets.QPushButton(self.groupBox_8)
        self.pipe_damage_modeling_button.setGeometry(QtCore.QRect(30, 40, 101, 23))
        self.pipe_damage_modeling_button.setObjectName("pipe_damage_modeling_button")
        self.node_damage_modeling_button = QtWidgets.QPushButton(self.groupBox_8)
        self.node_damage_modeling_button.setGeometry(QtCore.QRect(150, 40, 101, 23))
        self.node_damage_modeling_button.setObjectName("node_damage_modeling_button")
        self.label_20 = QtWidgets.QLabel(self.damage_tab)
        self.label_20.setGeometry(QtCore.QRect(200, 50, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.damage_directory_browse_button = QtWidgets.QPushButton(self.damage_tab)
        self.damage_directory_browse_button.setGeometry(QtCore.QRect(580, 70, 75, 23))
        self.damage_directory_browse_button.setObjectName("damage_directory_browse_button")
        self.damage_direcotry_line = QtWidgets.QLineEdit(self.damage_tab)
        self.damage_direcotry_line.setGeometry(QtCore.QRect(200, 70, 371, 20))
        self.damage_direcotry_line.setReadOnly(True)
        self.damage_direcotry_line.setObjectName("damage_direcotry_line")
        self.load_scenario_button = QtWidgets.QPushButton(self.damage_tab)
        self.load_scenario_button.setGeometry(QtCore.QRect(20, 230, 51, 23))
        self.load_scenario_button.setObjectName("load_scenario_button")
        self.save_scenario_button = QtWidgets.QPushButton(self.damage_tab)
        self.save_scenario_button.setGeometry(QtCore.QRect(20, 260, 51, 23))
        self.save_scenario_button.setObjectName("save_scenario_button")
        self.validate_scenario_button = QtWidgets.QPushButton(self.damage_tab)
        self.validate_scenario_button.setGeometry(QtCore.QRect(570, 350, 171, 41))
        self.validate_scenario_button.setObjectName("validate_scenario_button")
        self.groupBox_11 = QtWidgets.QGroupBox(self.damage_tab)
        self.groupBox_11.setGeometry(QtCore.QRect(560, 300, 171, 51))
        self.groupBox_11.setObjectName("groupBox_11")
        self.file_type_excel_radio = QtWidgets.QRadioButton(self.groupBox_11)
        self.file_type_excel_radio.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.file_type_excel_radio.setChecked(True)
        self.file_type_excel_radio.setObjectName("file_type_excel_radio")
        self.file_type_pickle_radio = QtWidgets.QRadioButton(self.groupBox_11)
        self.file_type_pickle_radio.setGeometry(QtCore.QRect(90, 20, 82, 17))
        self.file_type_pickle_radio.setObjectName("file_type_pickle_radio")
        self.main_process1.addTab(self.damage_tab, "")
        self.restoration_tab = QtWidgets.QWidget()
        self.restoration_tab.setObjectName("restoration_tab")
        self.groupBox = QtWidgets.QGroupBox(self.restoration_tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 191, 80))
        self.groupBox.setObjectName("groupBox")
        self.restoration_on_radio = QtWidgets.QRadioButton(self.groupBox)
        self.restoration_on_radio.setGeometry(QtCore.QRect(20, 40, 61, 17))
        self.restoration_on_radio.setChecked(True)
        self.restoration_on_radio.setObjectName("restoration_on_radio")
        self.restoration_off_radio = QtWidgets.QRadioButton(self.groupBox)
        self.restoration_off_radio.setGeometry(QtCore.QRect(90, 40, 82, 17))
        self.restoration_off_radio.setObjectName("restoration_off_radio")
        self.groupBox_2 = QtWidgets.QGroupBox(self.restoration_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 120, 731, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.policy_browse_button = QtWidgets.QPushButton(self.groupBox_2)
        self.policy_browse_button.setGeometry(QtCore.QRect(460, 100, 91, 23))
        self.policy_browse_button.setObjectName("policy_browse_button")
        self.script_rrp_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.script_rrp_radio.setGeometry(QtCore.QRect(290, 60, 111, 17))
        self.script_rrp_radio.setObjectName("script_rrp_radio")
        self.script_txt_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.script_txt_radio.setGeometry(QtCore.QRect(180, 60, 101, 17))
        self.script_txt_radio.setChecked(True)
        self.script_txt_radio.setObjectName("script_txt_radio")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.policy_definition_addr_line = QtWidgets.QLineEdit(self.groupBox_2)
        self.policy_definition_addr_line.setGeometry(QtCore.QRect(170, 100, 281, 20))
        self.policy_definition_addr_line.setText("")
        self.policy_definition_addr_line.setReadOnly(True)
        self.policy_definition_addr_line.setObjectName("policy_definition_addr_line")
        self.policy_designer = QtWidgets.QPushButton(self.groupBox_2)
        self.policy_designer.setGeometry(QtCore.QRect(460, 60, 91, 23))
        self.policy_designer.setObjectName("policy_designer")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 180, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.minimum_job_time_line = QtWidgets.QLineEdit(self.groupBox_2)
        self.minimum_job_time_line.setGeometry(QtCore.QRect(170, 180, 51, 20))
        self.minimum_job_time_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minimum_job_time_line.setObjectName("minimum_job_time_line")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setEnabled(False)
        self.label_14.setGeometry(QtCore.QRect(30, 140, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.crew_availability_browse_button = QtWidgets.QPushButton(self.groupBox_2)
        self.crew_availability_browse_button.setEnabled(False)
        self.crew_availability_browse_button.setGeometry(QtCore.QRect(460, 140, 91, 23))
        self.crew_availability_browse_button.setObjectName("crew_availability_browse_button")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(170, 140, 281, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(230, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(30, 60, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.groupBox_9 = QtWidgets.QGroupBox(self.restoration_tab)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 370, 721, 91))
        self.groupBox_9.setObjectName("groupBox_9")
        self.pipe_damage_discovery_button = QtWidgets.QPushButton(self.groupBox_9)
        self.pipe_damage_discovery_button.setGeometry(QtCore.QRect(30, 40, 75, 23))
        self.pipe_damage_discovery_button.setObjectName("pipe_damage_discovery_button")
        self.node_damage_discovery_button = QtWidgets.QPushButton(self.groupBox_9)
        self.node_damage_discovery_button.setGeometry(QtCore.QRect(120, 40, 75, 23))
        self.node_damage_discovery_button.setObjectName("node_damage_discovery_button")
        self.pump_damage_discovery_button = QtWidgets.QPushButton(self.groupBox_9)
        self.pump_damage_discovery_button.setGeometry(QtCore.QRect(210, 40, 75, 23))
        self.pump_damage_discovery_button.setObjectName("pump_damage_discovery_button")
        self.tank_damage_discovery_button = QtWidgets.QPushButton(self.groupBox_9)
        self.tank_damage_discovery_button.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.tank_damage_discovery_button.setObjectName("tank_damage_discovery_button")
        self.groupBox_10 = QtWidgets.QGroupBox(self.restoration_tab)
        self.groupBox_10.setGeometry(QtCore.QRect(30, 470, 211, 51))
        self.groupBox_10.setObjectName("groupBox_10")
        self.out_of_zone_travel_yes = QtWidgets.QRadioButton(self.groupBox_10)
        self.out_of_zone_travel_yes.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.out_of_zone_travel_yes.setObjectName("out_of_zone_travel_yes")
        self.out_of_zone_travel_no = QtWidgets.QRadioButton(self.groupBox_10)
        self.out_of_zone_travel_no.setGeometry(QtCore.QRect(90, 20, 101, 17))
        self.out_of_zone_travel_no.setChecked(True)
        self.out_of_zone_travel_no.setObjectName("out_of_zone_travel_no")
        self.main_process1.addTab(self.restoration_tab, "")
        self.run_tab = QtWidgets.QWidget()
        self.run_tab.setObjectName("run_tab")
        self.run_button = QtWidgets.QPushButton(self.run_tab)
        self.run_button.setGeometry(QtCore.QRect(260, 320, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.run_button.setFont(font)
        self.run_button.setObjectName("run_button")
        self.progressBar = QtWidgets.QProgressBar(self.run_tab)
        self.progressBar.setGeometry(QtCore.QRect(60, 380, 671, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.main_process1.addTab(self.run_tab, "")
        self.result_tab = QtWidgets.QWidget()
        self.result_tab.setObjectName("result_tab")
        self.main_process1.addTab(self.result_tab, "")
        self.main_tab.addTab(self.main_process, "")
        self.post_process = QtWidgets.QWidget()
        self.post_process.setObjectName("post_process")
        self.label_24 = QtWidgets.QLabel(self.post_process)
        self.label_24.setGeometry(QtCore.QRect(90, 120, 81, 16))
        self.label_24.setObjectName("label_24")
        self.tableWidget = QtWidgets.QTableWidget(self.post_process)
        self.tableWidget.setGeometry(QtCore.QRect(90, 520, 181, 161))
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.all_scenarios_checkbox = QtWidgets.QCheckBox(self.post_process)
        self.all_scenarios_checkbox.setGeometry(QtCore.QRect(250, 80, 121, 17))
        self.all_scenarios_checkbox.setChecked(False)
        self.all_scenarios_checkbox.setObjectName("all_scenarios_checkbox")
        self.mpl_curve = MplWidget(self.post_process)
        self.mpl_curve.setGeometry(QtCore.QRect(90, 190, 531, 291))
        self.mpl_curve.setObjectName("mpl_curve")
        self.curve_type_combo = QtWidgets.QComboBox(self.post_process)
        self.curve_type_combo.setGeometry(QtCore.QRect(90, 150, 351, 22))
        self.curve_type_combo.setObjectName("curve_type_combo")
        self.curve_type_combo.addItem("")
        self.curve_type_combo.addItem("")
        self.label_23 = QtWidgets.QLabel(self.post_process)
        self.label_23.setGeometry(QtCore.QRect(90, 500, 47, 13))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.post_process)
        self.label_25.setGeometry(QtCore.QRect(90, 60, 81, 16))
        self.label_25.setObjectName("label_25")
        self.scenario_combo = QtWidgets.QComboBox(self.post_process)
        self.scenario_combo.setGeometry(QtCore.QRect(90, 80, 141, 22))
        self.scenario_combo.setObjectName("scenario_combo")
        self.save_curve_button = QtWidgets.QPushButton(self.post_process)
        self.save_curve_button.setGeometry(QtCore.QRect(310, 550, 75, 23))
        self.save_curve_button.setObjectName("save_curve_button")
        self.main_tab.addTab(self.post_process, "")
        Opening_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Opening_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Opening_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Opening_Window)
        self.statusbar.setObjectName("statusbar")
        Opening_Window.setStatusBar(self.statusbar)
        self.action_Open_Project = QtWidgets.QAction(Opening_Window)
        self.action_Open_Project.setObjectName("action_Open_Project")
        self.action_Save = QtWidgets.QAction(Opening_Window)
        self.action_Save.setObjectName("action_Save")
        self.action_Save_Project_As = QtWidgets.QAction(Opening_Window)
        self.action_Save_Project_As.setObjectName("action_Save_Project_As")
        self.action_Exit = QtWidgets.QAction(Opening_Window)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(Opening_Window)
        self.action_About.setObjectName("action_About")
        self.action_REWET_GITHUB = QtWidgets.QAction(Opening_Window)
        self.action_REWET_GITHUB.setObjectName("action_REWET_GITHUB")
        self.menuFile.addAction(self.action_Open_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_Project_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menuHelp.addAction(self.action_REWET_GITHUB)
        self.menuHelp.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Opening_Window)
        self.main_tab.setCurrentIndex(0)
        self.main_process1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Opening_Window)

    def retranslateUi(self, Opening_Window):
        _translate = QtCore.QCoreApplication.translate
        Opening_Window.setWindowTitle(_translate("Opening_Window", "REWET"))
        self.groupBox_4.setTitle(_translate("Opening_Window", "Temp File Settings"))
        self.label_29.setText(_translate("Opening_Window", "Save time step"))
        self.save_time_step_yes_radio.setText(_translate("Opening_Window", "Yes"))
        self.label_30.setText(_translate("Opening_Window", "WARNING: Producing INP files for each event time can produce too many files"))
        self.save_time_step_no_radio.setText(_translate("Opening_Window", "No"))
        self.label_15.setText(_translate("Opening_Window", "Temp Folder"))
        self.temp_browser_button.setText(_translate("Opening_Window", "Browse"))
        self.groupBox_5.setTitle(_translate("Opening_Window", "Settings"))
        self.simulation_time_line.setText(_translate("Opening_Window", "36000"))
        self.label.setText(_translate("Opening_Window", "Simulation time"))
        self.label_32.setText(_translate("Opening_Window", "Run Type"))
        self.multiple_radio.setText(_translate("Opening_Window", "Multiple Serial"))
        self.single_radio.setText(_translate("Opening_Window", "Single"))
        self.label_3.setText(_translate("Opening_Window", "Simulation time step"))
        self.simulation_time_step_line.setText(_translate("Opening_Window", "3600"))
        self.label_17.setText(_translate("Opening_Window", "seconds"))
        self.label_18.setText(_translate("Opening_Window", "seconds"))
        self.result_directory_browser_button.setText(_translate("Opening_Window", "Browse"))
        self.label_22.setText(_translate("Opening_Window", "Result Folder"))
        self.main_process1.setTabText(self.main_process1.indexOf(self.simulation_tab), _translate("Opening_Window", "Simulation"))
        self.groupBox_3.setTitle(_translate("Opening_Window", "Solver Options"))
        self.label_9.setText(_translate("Opening_Window", "Solver:"))
        self.wntr_solver_radio.setText(_translate("Opening_Window", "WNTR"))
        self.modified_epanet_radio.setText(_translate("Opening_Window", "Modified EPANET V2.2"))
        self.minimum_pressure_line.setText(_translate("Opening_Window", "8"))
        self.required_pressure_line.setText(_translate("Opening_Window", "25"))
        self.label_10.setText(_translate("Opening_Window", "P(min):"))
        self.label_11.setText(_translate("Opening_Window", "h (water)"))
        self.label_12.setText(_translate("Opening_Window", "h (water)"))
        self.label_13.setText(_translate("Opening_Window", "P(req):"))
        self.label_4.setText(_translate("Opening_Window", "Hydraulic time step"))
        self.hydraulic_time_step_line.setText(_translate("Opening_Window", "3600"))
        self.label_16.setText(_translate("Opening_Window", "seconds"))
        self.groupBox_6.setTitle(_translate("Opening_Window", "Water Distribution Network"))
        self.wdn_browse_button.setText(_translate("Opening_Window", "Browse"))
        self.label_2.setText(_translate("Opening_Window", "System INP File"))
        self.demand_ratio_line.setText(_translate("Opening_Window", "1"))
        self.label_7.setText(_translate("Opening_Window", "Calibrate Demand"))
        self.label_8.setText(_translate("Opening_Window", "0<Ratio=<1"))
        self.main_process1.setTabText(self.main_process1.indexOf(self.hudrauics_tab), _translate("Opening_Window", "Hydraulics"))
        item = self.scenario_table.horizontalHeaderItem(0)
        item.setText(_translate("Opening_Window", "Name"))
        item = self.scenario_table.horizontalHeaderItem(1)
        item.setText(_translate("Opening_Window", "Pipe"))
        item = self.scenario_table.horizontalHeaderItem(2)
        item.setText(_translate("Opening_Window", "Node"))
        item = self.scenario_table.horizontalHeaderItem(3)
        item.setText(_translate("Opening_Window", "Pump"))
        item = self.scenario_table.horizontalHeaderItem(4)
        item.setText(_translate("Opening_Window", "Tank"))
        item = self.scenario_table.horizontalHeaderItem(5)
        item.setText(_translate("Opening_Window", "Probability"))
        self.label_31.setText(_translate("Opening_Window", "Damage Scenario"))
        self.add_scenario_button.setText(_translate("Opening_Window", "Add"))
        self.status_text.setHtml(_translate("Opening_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.remove_scenario_button.setText(_translate("Opening_Window", "Remove"))
        self.groupBox_7.setTitle(_translate("Opening_Window", "File Headers Correction"))
        self.pushButton_13.setText(_translate("Opening_Window", "Pipe"))
        self.pushButton_17.setText(_translate("Opening_Window", "Node"))
        self.pushButton_16.setText(_translate("Opening_Window", "Tanks"))
        self.pushButton_15.setText(_translate("Opening_Window", "Pump"))
        self.groupBox_8.setTitle(_translate("Opening_Window", "Damage Modeling"))
        self.pipe_damage_modeling_button.setText(_translate("Opening_Window", "Pipe"))
        self.node_damage_modeling_button.setText(_translate("Opening_Window", "Nodal"))
        self.label_20.setText(_translate("Opening_Window", "Damage File Directory"))
        self.damage_directory_browse_button.setText(_translate("Opening_Window", "Browse"))
        self.load_scenario_button.setText(_translate("Opening_Window", "Load"))
        self.save_scenario_button.setText(_translate("Opening_Window", "Save"))
        self.validate_scenario_button.setText(_translate("Opening_Window", "Validate Damage Scenarios"))
        self.groupBox_11.setTitle(_translate("Opening_Window", "File Type"))
        self.file_type_excel_radio.setText(_translate("Opening_Window", "Excel"))
        self.file_type_pickle_radio.setText(_translate("Opening_Window", "Pickle"))
        self.main_process1.setTabText(self.main_process1.indexOf(self.damage_tab), _translate("Opening_Window", "Damage"))
        self.groupBox.setTitle(_translate("Opening_Window", "On/Off"))
        self.restoration_on_radio.setText(_translate("Opening_Window", "On"))
        self.restoration_off_radio.setText(_translate("Opening_Window", "Off"))
        self.groupBox_2.setTitle(_translate("Opening_Window", "Restoration Definition"))
        self.policy_browse_button.setText(_translate("Opening_Window", "Browse"))
        self.script_rrp_radio.setText(_translate("Opening_Window", "Policy File (*.rrp)"))
        self.script_txt_radio.setText(_translate("Opening_Window", "Script (*.txt)"))
        self.label_5.setText(_translate("Opening_Window", "Policy Definition File"))
        self.policy_designer.setText(_translate("Opening_Window", "Policy Designer"))
        self.label_6.setText(_translate("Opening_Window", "Minimum Job Time"))
        self.minimum_job_time_line.setText(_translate("Opening_Window", "3600"))
        self.label_14.setText(_translate("Opening_Window", "Crew Availability"))
        self.crew_availability_browse_button.setText(_translate("Opening_Window", "Browse"))
        self.label_19.setText(_translate("Opening_Window", "seconds"))
        self.label_21.setText(_translate("Opening_Window", "File Type"))
        self.groupBox_9.setTitle(_translate("Opening_Window", "Damage Discovery"))
        self.pipe_damage_discovery_button.setText(_translate("Opening_Window", "Pipe "))
        self.node_damage_discovery_button.setText(_translate("Opening_Window", "Node"))
        self.pump_damage_discovery_button.setText(_translate("Opening_Window", "Pump"))
        self.tank_damage_discovery_button.setText(_translate("Opening_Window", "Tank"))
        self.groupBox_10.setTitle(_translate("Opening_Window", "Crew out-of-zone Travel"))
        self.out_of_zone_travel_yes.setText(_translate("Opening_Window", "Allowed"))
        self.out_of_zone_travel_no.setText(_translate("Opening_Window", "Not Allowed"))
        self.main_process1.setTabText(self.main_process1.indexOf(self.restoration_tab), _translate("Opening_Window", "Restoration"))
        self.run_button.setText(_translate("Opening_Window", "RUN"))
        self.main_process1.setTabText(self.main_process1.indexOf(self.run_tab), _translate("Opening_Window", "Run"))
        self.main_process1.setTabText(self.main_process1.indexOf(self.result_tab), _translate("Opening_Window", "Result"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.main_process), _translate("Opening_Window", "Process"))
        self.label_24.setText(_translate("Opening_Window", "Curve Type"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Opening_Window", "Percentage"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Opening_Window", "Leak Ratio"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Opening_Window", "Time Unit"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Opening_Window", "Time Shift"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Opening_Window", "Values"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.all_scenarios_checkbox.setText(_translate("Opening_Window", "All Scenarios"))
        self.curve_type_combo.setItemText(0, _translate("Opening_Window", "Quantity Exceedance"))
        self.curve_type_combo.setItemText(1, _translate("Opening_Window", "Delivery Exceedance"))
        self.label_23.setText(_translate("Opening_Window", "Settings"))
        self.label_25.setText(_translate("Opening_Window", "Scenario"))
        self.save_curve_button.setText(_translate("Opening_Window", "Save"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.post_process), _translate("Opening_Window", "Post-Process"))
        self.menuFile.setTitle(_translate("Opening_Window", "File"))
        self.menuHelp.setTitle(_translate("Opening_Window", "Help"))
        self.action_Open_Project.setText(_translate("Opening_Window", "Open Project"))
        self.action_Save.setText(_translate("Opening_Window", "Save"))
        self.action_Save_Project_As.setText(_translate("Opening_Window", "Save Project As"))
        self.action_Exit.setText(_translate("Opening_Window", "Exit"))
        self.action_About.setText(_translate("Opening_Window", "About"))
        self.action_REWET_GITHUB.setText(_translate("Opening_Window", "REWET GITHUB"))
from .MplWidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Opening_Window = QtWidgets.QMainWindow()
    ui = Ui_Opening_Window()
    ui.setupUi(Opening_Window)
    Opening_Window.show()
    sys.exit(app.exec_())
